export const homeObjOne = {
  id: 'about',
  lightBg: true,
  lightText: false,
  darkText: true,
  lightTextDesc: false,
  topLine: 'July 2015 - June 2020',
  headline: 'Bachelor of Science: Computer Science',
  description: 'I went to school and took tests.  Homework.  Now I am smart.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/png-1.png').default,
  alt: 'Car',
  dark: true,
  primary: true,
};

export const homeObjTwo = {
  id: 'discover',
  lightBg: false,
  lightText: true,
  darkText: false,
  lightTextDesc: false,
  topLine: 'October 2005 - July 2015',
  headline: 'Marine Science Technician',
  description: 'I did really cool things and got paid very little.  Now I get discounts and tell sea stories.',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/svg-5.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
};

export const homeObjThree = {
  id: 'services',
  lightBg: true,
  lightText: false,
  darkText: true,
  lightTextDesc: false,
  topLine: 'October 2005 - July 2015',
  headline: 'Marine Science Technician',
  description: 'I did really cool things and got paid very little.  Now I get discounts and tell sea stories.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
};
